# MySQL (perfil mysql)
spring.config.import=optional:file:.env.dev[.properties]
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DB_NAME:marketplace}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
